### ISSUE TITLE
After installation, it is unclear how to start the program

### ISSUE THREAD

**Issue by NameOfTheDragon** [ASCOMInitiative/ASCOMDeviceHub#1]
Right after installing the ASCOM Device hub, when the user tries to run it, there is no obvious method to do so. The installer does not create a start menu entry and this runs contrary to the principle of "least astonishment".

It turns out that the installer did create a desktop shortcut, but I have a busy desktop and it was completely lost in the noise. The first place a user is going to look is on the start menu, not the desktop.

**Desired outcome**: have the installer create a start menu entry.

**Comment by astroman133** [comment]
The version 6.4.1.3 installer now creates a shortcut on the Windows Start Menu.

**Comment by NameOfTheDragon** [comment]
Works perfectly, thank you @astroman133
