### ISSUE TITLE
script question

### ISSUE THREAD

**Issue by Rojoyinc** [ASCOMInitiative/ASCOMDeviceHub#11]
I have a script I've been running and would like to add a  "disconnect mount" and "disconnect dome"
call in the script.  How would I do that (is there a list of script info?  
This what I have currently. 

var dome;
var hub;
 //     var mount;

dome = new ActiveXObject("ASCOM.NexDome.Dome");
hub = new ActiveXObject("ASCOM.DeviceHub.Dome");

dome.Connected = true;

hub.Connected = true;

while (dome.ShutterStatus == 4);    // Error - wait for shutter to go online

dome.CloseShutter();
dome.FindHome();
dome.Park();

hub.slaved = false;

dome.Connected = false;
hub.Connected = false;

dome.Dispose();
hub.Dispose();

dome = null;
hub = null;

var oShell = WScript.CreateObject("WScript.Shell");
var oExec = oShell.Exec('Wscript C:\ParkRasa.vbs PARK_ANGLE');

**Comment by astroman133** [comment]
This is a how-to question, not an issue with DeviceHub. Marking it as closed.
