### ISSUE TITLE
Connect 32bit only telescope driver problem

### ISSUE THREAD

**Issue by fockez** [ASCOMInitiative/ASCOMDeviceHub#13]
Here we got astrometric telescope mount, it uses maestro3 and have ascom driver. When I try to connect this telescope with 64 bit python, it is said that the driver is 32 bit only.
So I think about the DeviceHub, and try to connect the mount via device hub.
But when I try to connect, it fails at last and let me check the Log, but there is no log at My Documents\ASCOM
I want to make sure that it is really no possible connect this 32 bit driver from 64 platform.
thanks

**Comment by astroman133** [comment]
When used correctly DeviceHub will allow a 64-bit application to use a 32-bit only driver.

In order to have logs created in C:\Users\<your username>\Documents\ASCOM you must enable logging in the Setup dialog for DeviceHub and for the driver for your mount.

Since your posts are questions about how to use Device Hub rather than a programming issue with Device Hub, please post in the ASCOM Talk forum on Groups.io.

**Comment by fockez** [comment]
OK, I got the logs. I posts to here because I thought it reports as unhandled exception, not use case. I can use the device hub with other telescopes.

21:32:22.644: Telescope - Others:       Get Connected flag - True
21:32:22.644: Telescope - Others:       Get Connected flag - True
21:32:23.707: Telescope - Capabilities: Get CanFindHome: False
21:32:23.707: Telescope - Capabilities: Get CanPark: False
21:32:23.707: Telescope - Capabilities: Get CanPulseGuide: True
21:32:23.707: Telescope - Capabilities: Get CanSetDeclinationRate: False
21:32:23.707: Telescope - Capabilities: Get CanSetGuideRates: False
21:32:23.707: Telescope - Capabilities: Get CanSetPark: True
21:32:23.707: Telescope - Capabilities: Get CanSetPierSide: False
21:32:23.707: Telescope - Capabilities: Get CanSetRightAscensionRate: False
21:32:23.707: Telescope - Capabilities: Get CanSetTracking: True
21:32:23.707: Telescope - Capabilities: Get CanSlew: True
21:32:23.707: Telescope - Capabilities: Get CanSlewAltAz: True
21:32:23.707: Telescope - Capabilities: Get CanSlewAltAzAsync: True
21:32:23.722: Telescope - Capabilities: Get CanSlewAsync: True
21:32:23.722: Telescope - Capabilities: Get CanSync: True
21:32:23.722: Telescope - Capabilities: Get CanSyncAltAz: True
21:32:23.722: Telescope - Capabilities: Get CanUnpark: False
21:32:23.722: Telescope - Capabilities: Calling CanMoveAxis( Primary )False
21:32:23.722: Telescope - Capabilities: Calling CanMoveAxis( Secondary )False
21:32:23.722: Telescope - Capabilities: Calling CanMoveAxis( Tertiary )False
21:32:23.722: Telescope - Capabilities: Calling AxisRates( Primary )(done)
21:32:23.722: Telescope - Capabilities: Calling AxisRates( Secondary )(done)
21:32:23.722: Telescope - Capabilities: Calling AxisRates( Tertiary )(done)
21:32:23.722: Telescope - Parameters:   Get AlignmentMode: algPolar
21:32:23.769: Telescope - Parameters:   Get ApertureArea Exception: Property read Maestro.Telescope ApertureArea is not implemented in this driver.
21:32:23.769: Telescope - Parameters:   Get ApertureDiameter Exception: Property read Maestro.Telescope ApertureDiameter is not implemented in this driver.
21:32:23.769: Telescope - Parameters:   Get Description: Telescope controlled by Astrometric Telescope Control System (ATCS)
21:32:23.769: Telescope - Parameters:   Get DriverInfo: Maestro's ASCOM telescope driver
Driver Version = 1.3.0
Astrometric Instruments, Inc.
Copyright © 2005-2014, Astrometric Instruments, Inc.
ASCOM interface to ATCS (through Maestro).  Visit www.astrometric.com for more info
21:32:23.769: Telescope - Parameters:   Get DoesRefraction: False
21:32:23.769: Telescope - Parameters:   Get DriverVersion: 1.3
21:32:23.785: Telescope - Parameters:   Get EquatorialSystem: equLocalTopocentric
21:32:23.785: Telescope - Parameters:   Get FocalLength Exception: Property read Maestro.Telescope FocalLength is not implemented in this driver.
21:32:23.785: Telescope - Parameters:   Get InterfaceVersion: 2
21:32:23.785: Telescope - Parameters:   Get SiteElevation Exception: Property read Maestro.Telescope SiteElevation is not implemented in this driver.
21:32:23.785: Telescope - Parameters:   Get SiteLatitude: 38.5888888888889
21:32:23.785: Telescope - Parameters:   Get SiteLongitude: 93.8863888888889
21:32:23.785: Telescope - Parameters:   Get SlewSettleTime: 0
21:32:23.785: Telescope - Parameters:   Get SupportedActions: System.Collections.ArrayList 
21:32:23.800: Telescope - Parameters:   Get TrackingRates:21:32:23.800: Telescope - Others:       Attempting to initialize telescope operation caught an unhandled exception. Details follow:
21:32:23.816: Telescope - Others:       System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at ASCOM.DriverAccess.TrackingRates.get_Count() in C:\ASCOM Build\Export\ASCOM.DriverAccess\Telescope.cs:line 1565
   at ASCOM.DeviceHub.DeviceManagerBase.GetServiceProperty[T](Func`1 getCmd, T defaultValue, ActivityMessageTypes messageType, String propName) in D:\My Projects\Visual Studio 2019\ASCOM\ASCOMDeviceHub\DeviceHub\DeviceManagers\DeviceManagerBase.cs:line 93
   at ASCOM.DeviceHub.TelescopeManager.get_TrackingRates() in D:\My Projects\Visual Studio 2019\ASCOM\ASCOMDeviceHub\DeviceHub\DeviceManagers\TelescopeManagerAccess.cs:line 440
   at ASCOM.DeviceHub.TelescopeParameters..ctor(TelescopeManager mgr) in D:\My Projects\Visual Studio 2019\ASCOM\ASCOMDeviceHub\DeviceHub\Business Object Classes\Telescope Classes\TelescopeParameters.cs:line 38
   at ASCOM.DeviceHub.TelescopeManager.ReadInitialTelescopeDataTask() in D:\My Projects\Visual Studio 2019\ASCOM\ASCOMDeviceHub\DeviceHub\DeviceManagers\TelescopeManager.cs:line 910
   at ASCOM.DeviceHub.TelescopeManager.<Connect>b__234_0() in D:\My Projects\Visual Studio 2019\ASCOM\ASCOMDeviceHub\DeviceHub\DeviceManagers\TelescopeManager.cs:line 213
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
21:32:23.816: Telescope - Others:       Set Connected flag -> False (failed)
21:32:34.097: Telescope - Others:       Disconnection failed after 10000 milliseconds
21:32:34.097: Telescope - Others:       Get Connected flag - 
21:32:34.097: Telescope - Others:       Get Connected flag -

**Comment by astroman133** [comment]
DeviceHub is getting an error when trying to read the Tracking Rates supported by the Maestro's Telescope driver. According to the ASCOM Telescope specification the driver must have this property and must return a valid list of tracking rates. 

This is a problem with the driver and you need to report the issue to the driver's authors. They should also test the driver with the ASCOM Comform test application to ensure that it complies with the specification. If they have questions about writing a compliant driver they should ask them on the ASCOM Developer subforum on Groups.io.

Thank you.

**Comment by fockez** [comment]
OK, I see it. Thanks. I will try to connect the astrometric.
