### ISSUE TITLE
CanSlave and Slaved

### ISSUE THREAD

**Issue by BobDenny** [ASCOMInitiative/ASCOMDeviceHub#15]
Since DeviceHub can provide full-function slaving (thanks!!), I would like to request that the Dome.CanSlave property return True if there is a connected telescope, then Dome.Slaved would control the "Slaved to Telescope" checkbox in the Dome Control area, Dome State.  This request comes from [this post on ASCOM Help](https://ascomtalk.groups.io/g/Help/message/46961).

**Comment by astroman133** [comment]
The CanXXX properties are typically static properties of a driver so for this reason, the Device Hub Dome driver always returns True for CanSlave.

When an application attempts to set Slaved to True additional capabilities and statuses are checked to determine if the dome and telescope are in a state that supports slaving. Below are the additional prerequisites:

1) The underlying dome driver must support the ability to rotate the dome by setting the Azimuth property
2) Device Hub must be able to read the Telescope Status Properties and a telescope must be Connected
3) The underlying Telescope driver's RightAscension, Altitude, and Azimuth must have been read and must be reasonable values
4) The underlying Telescope driver's SiteElevation, SiteLatitude, and SiteLongitude properties must have been accurately set
5) Telescope slewing must support the J2000 or JNOW coordinate systems.

If the above conditions are met and the Dome driver Slaved property has been set to True by either a connected application or through the DH user interface then the SlavedToTelescope checkbox will be checked, as requested, and  DH will attempt to slew the dome to a position that places the slit over the telescope. Additional data, such as the X, Y, and Z distance from the center of the dome to the telescope will be used to calculate a dome azimuth, and optionally altitude and an attempt will be made to move it there, if any movement is required. If DH gets this far then the Dome Command Activity Log will show what is occurring.

**Comment by astroman133** [comment]
No response to my explanation, so I am adding another comment.

Based on the request and my examination of current behavior, DH already does what is requested.

Here is the code from the DH Dome driver for the CanSlave property.

`		public bool CanSlave
		{
			get
			{
				bool retval = true;

				LogMessage( "Get CanSlave:", retval.ToString() );

				return retval;
			}
		}`

As you can see, the driver is hardcoded to always return True.
