### ISSUE TITLE
Wait for mount slew before dome moves

### ISSUE THREAD

**Issue by Rojoyinc** [ASCOMInitiative/ASCOMDeviceHub#2]
A minor annoyance. There is one wait...  if to short. The dome keeps chasing the slew and stopping and chasing. Also this timer (also sets time between slaves) I suspect as it seems to. 
I want time between slave updates to be longer. (maybe 1 minute or 90 seconds) else my dome is kicking in every 10 seconds to slave/align to mount.  (wearing out hardware). 

If I set this longer, then it waits say 60 seconds for the mount to slew. (if it's not done yet) it will start to slave to the mount and stop. (since the mount might be doing a flip). The mount then finishes and the dome is waiting 60-90 seconds  AGAIN before it will finish slaving to the final pointing position of the mount. During this time my other software doing the capture starts to do a plate solve after the flip and since it takes 60-90 seconds before the dome kicked in again... I get the inside of the dome to solve. (often causing problems). 

I was hoping we could have 2 timers. (one to update slaved position to the mount) so as it TRACKS slowly it slaves ever 90 seconds. 

Another that follows the mounts SLEW - so that it can be short and stay fairly tight with the scope during a flip. 

Hope I explained that well?

**Comment by Rojoyinc** [comment]
in a nutshell - a timer between  'slave updates" and a timer during (wait for slew).  I think sums it up.

**Comment by astroman133** [comment]
Can you please describe how you are connected? It sounds like you are not connected through the Device Hub Telescope driver. If you were then there should not be a slew/stop scenario because when the telescope starts to slew, the dome should very quickly start to slew to the position that it needs to be in when the telescope's slew is finished. In this case the movement is almost immediate, regardless of the value of the Slave Frequency timer interval The dome should move all in a single move. If you are connected to the mount outside of Device Hub then this is not the case.

Also I am confused about what you mean when you say "it will start to slave to the mount and stop". The design behavior is that the dome is slaved to the mount when you click the checkbox in the DH user interface or when the dome's Slaved property is set to true. It should stay slaved as long as those conditions remain.

Meridian flip is a different story. You may want to consider unslaving the dome during a flip, since the mount does a lot of movement and the scope would usually need to move only a few degrees, at most.

Thanks!

Rick

**Comment by Rojoyinc** [comment]
Hi Rick - thank you! for doing a new hub and taking over from Poth. 

Though poth worked in real-time. As the slew of the scope moved the slit in the dome would track with it. Then there was a tracking "update" (not time but I think it was error of degree) so it would update the slit position when the slew moved more than (x) amount (say 1 degree). 

![dome1](https://user-images.githubusercontent.com/19595691/74744914-0ccf2a80-5231-11ea-90ef-25722b6a3e7d.JPG)

btw - I love the dome azimuth adjustment slider. (in case) it needs a quick adjustment. 

when connected  Slave is checked.  (I can't connect now since RASA is being replaced. My com ports are in use so the dome doesn't find the correct com port. 

I see AMOUNT 1'  (is that slave correction during tracking?) .   
Then in settings, it says slave freq. (I have it at 8) because I want it to quickly follow the slew, but I don't want it to be so fast that it slaves (updates) ever 8 seconds.  Am I right in my way ot thinking? (or is the 1 degree (error for tracking correction) and 8 seconds is for slew delay? 

Thanks for the support! 

To clarify your 2nd paragraph. Let's say I start a large slew. (scope is moving,  dome starts to follow. (it waits? the 8 seconds I have set in settings).  If the scope has not completed the slew and the dome catches up to the scope position, the dome STOPS.  (then waits another (set in settings 8 seconds) to start to complete the alignment with the rest of slew.   If I have wait changed from 8 seconds to 50 seconds. It waits to align the dome for 50 seconds. Generally, the slew is then complete.  All is well. Unless it's not done slewing. And the dome stops prematurely, then waits 50 seconds again to follow the continuation of the slew. Then it gets there too late and I'm plate solving the inside of the dome.  (hard to explain).  

It sounds like (from what you say) there should be no slave delay? (then what is the  slave freq. setting?)    And is  slave precision (deg) I have set to 1.  (the tracking update?) I should change that to maybe 5?  So during tracking/exposures, it moves the dome less often?

I wish I could get it to connect (I might have to trudge in the snow and change com ports) because when it is connected. Under capabilities.  It lists all the options (true/false).  I can't see it now because I can't connect at this time. But I seem to recall it being "wierd" in that I am slaving but I seem to recall it saying   FALSE  for  Can Slave:    SOMETHING in that last read false and I thought that was odd.  Did my screen shots help at all? 

![dome2](https://user-images.githubusercontent.com/19595691/74747853-984aba80-5235-11ea-8c8c-d62d778861fa.JPG)

**Comment by Rojoyinc** [comment]
okay I got the dome working again (was battery dead) while waiting for new scope.  And I'm connected and SLAVED to the mount. (yes box is checked). And as I thought. This seems wrong.
Maybe this is the cause of my weird operation? 

![dome3](https://user-images.githubusercontent.com/19595691/74771661-88929c80-525c-11ea-970d-c5f746f57333.JPG)

**Comment by Rojoyinc** [comment]
Asking others in the nexdome fb group if theirs acts like mine. (and so far seems so).  You're saying it should slave "read time" with the dome?  Poth did.

**Comment by NameOfTheDragon** [comment]
@Rojoyinc Since you are using a NexDome, if your tracking updates are too frequent, you can increase your `Dead Zone` setting in the firmware (`@DWR,nnn`). This sets the smallest move that the dome will make.

**Comment by Rojoyinc** [comment]
Hi Tim, you solved it.  I updated to ASCOM and linked to the hub instead of the mount and it now tracks in real time. Will do on dead zone if it persists. 

RICK thanks - Tim got me sorted. Thanks for your work on the hub!

**Comment by astroman133** [comment]
Thanks, I am glad that you are up and running.

**Comment by astroman133** [comment]
I replied to the emails that I received from Rojoyinc from his posts here, but none of my emails show up. In my posts I mentioned several times that his issue was that he was not connected to his telescope through the Device Hub Telescope driver. I learned that in the future that I need to come to the github web site to reply. Thanks!
