### ISSUE TITLE
Dome Shutter Opening/Closing Errors

### ISSUE THREAD

**Issue by rfurmanimd** [ASCOMInitiative/ASCOMDeviceHub#4]
The ASCOM Device Hub Dome driver appears to exhibit a race condition between OpenShutter/CloseShutter methods and the ShutterStatus property when controlled by an external program.

My configuration is Voyager 2.2.8 -> ASCOM Device Hub 6.4.1.4 -> Digital Domeworks 2018 7.1.0.3 (https://forum.starkeeper.it/t/voyager-2-2-8-release/1325 and http://tigra-astronomy.com/ascom-drivers-for-digital-domeworks) testing using either physical hardware or Digital Domeworks driver simulation mode.

Occasionally the Voyager shutter open/close commands with Device Hub Dome succeed (see run 2 below). Opening and closing typically takes about 50 seconds.

Most times, however, when Voyager calls CloseShutter and then status
polls about every second for "shutterClosed [1]", Voyager reports an error because ShutterStatus unexpectedly returns either "shutterOpen [0]" (run 1 below) or "shutterError [4]" (not shown) 
after zero or more "shutterClosing [3]" messages. The physical shutter may or may not close after the Voyager error report. 

Less frequently a Voyager OpenShutter call will also produce a "shutterClosed [1]" (see run 3 below) message and fail.

When connecting Voyager either directly to Digital Domeworks 2018 or indirectly through POTH.Dome, I've never had a dome shutter error with Voyager over many months of running.

Limited testing using the ASCOM Device Hub GUI to manually control Digital Domeworks shutter did not show any problems opening or closing the shutter.

**Voyager -> Device Hub Dome -> Digital Domeworks 2018 close shutter error run 1:**
13:47:28 645 - Action Start
13:47:28 648 - Opening Dome Shutter ...
13:47:28 649 - Command OpenShutter Processed correctly ...
13:47:32 618 - Dome Shutter Status = shutterOpening [2]
...
13:48:14 779 - Dome Shutter Status = shutterOpening [2]
13:48:15 783 - Dome Shutter Status = shutterOpen [0]
13:48:15 787 - Dome Shutter Open
13:48:15 805 - Action Time [ATOMIC_DOME_CMD] => 0 [m] 47 [s] 
13:48:15 807 - Action Time Mobile Mean [ATOMIC_DOME_CMD] => 0 [m] 10 [s] 
13:48:15 855 - Action End : OK

13:48:26 347 - Action Start
13:48:26 351 - Closing Dome Shutter ...
13:48:26 354 - Command CloseShutter Processed correctly ...
13:48:30 319 - Dome Shutter Status = shutterOpen [0]
13:48:30 337 - Action Aborted for Error : Shutter result opened after starting closing !!!
13:48:30 339 - Action Time [ATOMIC_DOME_CMD] => 0 [m] 4 [s] 
13:48:30 343 - Action Time Mobile Mean [ATOMIC_DOME_CMD] => 0 [m] 10 [s] 
13:48:30 346 - Action End : FINISHED_ERROR

**Voyager -> Device Hub Dome -> Digital Domeworks 2018 Open/Close shutter success run 2:**
13:50:36 467 - Action Start
13:50:36 471 - Opening Dome Shutter ...
13:50:36 472 - Command OpenShutter Processed correctly ...
13:50:40 463 - Dome Shutter Status = shutterOpening [2]
...
13:51:22 638 - Dome Shutter Status = shutterOpening [2]
13:51:23 642 - Dome Shutter Status = shutterOpen [0]
13:51:23 645 - Dome Shutter Open
13:51:23 709 - Action Time [ATOMIC_DOME_CMD] => 0 [m] 47 [s] 
13:51:23 711 - Action Time Mobile Mean [ATOMIC_DOME_CMD] => 0 [m] 11 [s] 
13:51:23 714 - Action End : OK

13:51:31 528 - Action Start
13:51:31 536 - Closing Dome Shutter ...
13:51:31 556 - Command CloseShutter Processed correctly ...
13:51:35 514 - Dome Shutter Status = shutterClosing [3]
...
13:52:19 677 - Dome Shutter Status = shutterClosing [3]
13:52:20 680 - Dome Shutter Status = shutterClosed [1]
13:52:20 682 - Dome Shutter Closed
13:52:20 703 - Action Time [ATOMIC_DOME_CMD] => 0 [m] 49 [s] 
13:52:20 725 - Action Time Mobile Mean [ATOMIC_DOME_CMD] => 0 [m] 12 [s] 
13:52:20 729 - Action End : OK

**Voyager -> Device Hub Dome -> Digital Domeworks 2018 open shutter error run 3:**
2020/03/28 14:01:21 862 - INFO      - [Open Observatory Shutter     ] - [Funzione                                     ] - Action Start
2020/03/28 14:01:21 866 - INFO      - [DomeCMD                      ] - [OPEN_SHUTTER_Code                            ] - Opening Dome Shutter ...
2020/03/28 14:01:21 867 - INFO      - [DomeCMD                      ] - [OPEN_SHUTTER_Code                            ] - Command OpenShutter Processed correctly ...

2020/03/28 14:01:25 830 - DEBUG     - [DomeCMD                      ] - [OPEN_SHUTTER_WAIT_Code                       ] - Dome Shutter Status = shutterClosed [1]
2020/03/28 14:01:25 831 - CRITICAL  - [Open Observatory Shutter     ] - [Funzione                                     ] - Action Aborted for Error : Shutter result closed after starting opening !!!
2020/03/28 14:01:25 833 - INFO      - [ATOMIC_DOME_CMD              ] - [Funzione                                     ] - Action Time [ATOMIC_DOME_CMD] => 0 [m] 4 [s] 
2020/03/28 14:01:25 873 - INFO      - [ATOMIC_DOME_CMD              ] - [Funzione                                     ] - Action Time Mobile Mean [ATOMIC_DOME_CMD] => 0 [m] 12 [s] 
2020/03/28 14:01:25 875 - INFO      - [Open Observatory Shutter     ] - [Funzione                                     ] - Action End : FINISHED_ERROR

**Comment by astroman133** [comment]
Thank you for your detailed explanation of the issue. It made it simple to duplicate and repair.

It should be fixed in release v6.4.1.5
