### ISSUE TITLE
Mount isn't sharing DATA?  NO DATA

### ISSUE THREAD

**Issue by Rojoyinc** [ASCOMInitiative/ASCOMDeviceHub#9]
Love DH thanks for this effort. I've been using it just find for seems like a year now.  Last couple nights the dome will not sync properly.  Trying to find the problem I noticed often the Telescope STATE says connected... but NO DATA
over and over and side of pier West.

I'm latest version  as I tried to update first. I was using 6.4.1.5  when it started a couple nights ago. I updated to 6.4.1.11
and still no data.

Also (when new version uninstalls previous - can it keep the previous "SETTINGS"?  it's a pain to enter them all again.
Since I'm at it - when I go to sync AZ *under actions) the sync button is never highlighted?  it's greyed out. 

I find this also strange. Under capabilities...  it says
all TRUE except (can set alt) this should be false and is.
the next 3 are true and are.
The last two say  FALSE and should be true?    These are  Can slave  (says false?)  and Can sync Az false? (which is should be able to). I'm using a NexDome. 

Back to original Slaving issue. I'm using same old settings I've used for a year and "poth calc". Same as always.
I believe the slaving is lost due to NO DATA... (when if it connect again after a AZ tracking update it's probably off). 

![nodata](https://user-images.githubusercontent.com/19595691/90815686-15481100-e2f9-11ea-86a9-7debda91224e.JPG)
![cantslave](https://user-images.githubusercontent.com/19595691/90815687-15481100-e2f9-11ea-8f63-0a90b21deef3.JPG)
![wont-sync](https://user-images.githubusercontent.com/19595691/90815688-15481100-e2f9-11ea-8eae-f7fca4bd8ea8.JPG)

![mydomedriver](https://user-images.githubusercontent.com/19595691/90815746-2c86fe80-e2f9-11ea-9957-7e795942868a.JPG)

**Comment by Rojoyinc** [comment]
I just disconnected the mount and reconnected and this time I have data. But often do not? 
![just disconnected and reconnected and now they appear](https://user-images.githubusercontent.com/19595691/90816008-930c1c80-e2f9-11ea-8cdf-275521c8a89b.JPG)

**Comment by astroman133** [comment]
If DH is showing NO DATA then it is not reading data from the mount. If it is not reading data from the mount, then it will not be able to sync the dome to the mount.

There are several criteria that must be true in order for the Sync button to be enabled. They are:

1) DH must be connected with the dome and must have read the capabilities and status values
2) The dome must not be currently slewing
3) The downstream dome driver must support the CanSyncAzimuth property

The dome driver's CanSlave capability is probably correct at False. This property refers to the dome driver being able to sync with a telescope that is connected directly with your dome controller. If you are using DH to sync the dome with the scope then this MUST be False.

CanSyncAzimuth is read from the dome driver. As I said above when this is False, it will prevent the Sync Azimuth button from becoming enabled because the NexDome driver does not support this functionality.

Removal of a driver's Profile data when the driver is unregistered is normal behavior for ASCOM drivers. It is built into the driver templates that most driver authors use. I understand that it is a pain, but it is easy to save a screenshot to allow you to re-enter the data. I may ask what other driver authors are doing to see of there is a commonly adopted solution. It is probably in place to prevent the Profile from being littered with data from uninstalled drivers.

I have an AP mount, but do not use APCC. How are you connecting? Which driver is DH using?

Also the version of DH that is included with ASCOM 6.5 is slightly newer than what is posted in the DeviceHub repository. I do not plan to release new versions of DH outside of the ASCOM Platform. That said, I do not expect that the newer version would address your issues, which seem to be communications related.

The screenshots are insufficient for troubleshooting. Please provide Activity Logs and APCC or APV2 logs for one situation per post. Please do not enable everything and then just run. It will be very difficult to look through a huge log for what is going on for 5 separate issues that may or may not have happened when the logs were being collected.

If DH has worked for several months, but suddenly started having issues, then it is likely not a problem with DH. Please think about what else has changed in terms of other software, hardware, and cabling.

Thanks,

**Comment by Rojoyinc** [comment]
Thanks for the lengthy reply. I appreciate it.  I'm starting to wonder if I changed a driver during updating. 
Tonight I had the same thing HORRIBLE slaving. I had to unslave and do a "GOTO" and sit and update the position.

I do APCC and V2 driver v5.30.10

DEvice hub I load the astrophysicsV2.telescope driver.   On dome control in the hub I'm connecting to ascom.nexdome.dome driver.   This should allow the hub to slave the dome with the V2 driver from the mount?

I use NINA for capture/control and I can connect nina to the mount or to the hub then the hub to the mount. (which is what I normally do) This allows NINA to control the mount for GOTO's and plate solving.  I Also use stellarium which I use ascom control with it and connect stellarium to the device hub (for scope connection). 

I must have changed something but I'm unsure what. As nothing would have needed changing. I'll keep exploring here and see if I can share more insite... logs?  etc.  I'm really puzzled right now.

**Comment by Rojoyinc** [comment]
BTW - I had the problem severely tonight and watched the "DATA" in the device hub and I never saw it lose the data. It always had the info from the driver.  So apparently the DATA issue I mentioned before is not causing the slave issue.

**Comment by Rojoyinc** [comment]
After posting I went back into it and opened up and did goto and slave to about 8 targets. All were fine.  I went back to the target I've been doing this past week with nb runs and it was off again.  Just one North American neb. It was near zenith, but was not slaving properly all the way.  It might be a refinement needed in my slave settings. 
I did see the DATA always in the hub. 

Do you recommend I use my old POTH settings. Or should I uncheck that and adjust settings for DH instead?    Best calculations?

**Comment by Rojoyinc** [comment]
Again poor slaving on the tulip nebula (near the cygnus wall that I had problems with before). 
I had to manually position the dome. After the meridian flip I was able to get it to track fairly well.

I think before when I could SYNC.  I will redo my slave settings (again) I'd love to know about my previous question.
POTH? or no ? which will do best calculations for tracking the slit?

**Comment by Rojoyinc** [comment]
While it use to work perfectly (for 3 years with poth and then with device hub) it now can't seem to figure out where the slit is when very high near zenith.  The slit use to do a 180 to allow the scope to aim straight up.  I can't leave it automated all night like I use to.  I have to keep manually correcting the slit.  Turning off auto slew and doing manual goto direct motions from 0-359.

**Comment by astroman133** [comment]
Well, something changed to cause what was working to not work.
Your previous screenshot shows that you have the Dome Azimuth adjustment set to -9 degrees. That is a lot. Does the dome behave better when that is set at 0? The fact that you have to use that at all indicates that there is something wrong with your dome geometry settings. Have you double-checked them?

**Comment by Rojoyinc** [comment]
I double checked them from what I've used for years. 
-9 is often what I need to do to keep the scope centered in the slit now. 

I get another ERROR from nina and seems to stem from device hub.  Does this help?

![device hub error from nina](https://user-images.githubusercontent.com/19595691/92506135-f986ab00-f1d2-11ea-9460-b024e4fbd24e.JPG)

ABOVE (it does slew?  what is "direct slew")  to does GOTO and dome tracks (though not always accurately. I sometimes have to bump it  + and sometimes -  to get the slit aligned.

I have stellarium connect to ascom scope.  (device hub)
I have device hub connect to nexdome and to astrophysics mount. 
I have NINA connect to  device hub telescope

I'm not sure but I did change this up a short while ago. (did this mess it up?)

I think device hub does all the syncing of dome/mount?  I have heard that NINA will soon have dome support.  MAYBE that will solve the problem. 

I'm using ASCOM 6.4 as 6.5 is not recommended by NINA 1.1 yet. |

**Comment by Rojoyinc** [comment]
I'm trying to run tests to check slave settings.  MUST the shutter be open to slave the scope? It's raining currently and I know lots of guys like to test with shutter closed. It seems intermittent.

**Comment by Rojoyinc** [comment]
I wanted to spend the day working in this and not getting anything but non compliance. I opened the dome to get the driver to say open.  HUB won't slave and says closed?   I'm not sure but I THINK I have to open teh dome all the way to get hub to realize it's open?  (in the rain) then I want to have it nearly closed.   Can that be changed to read the open or closed status from the driver? 
![slave1](https://user-images.githubusercontent.com/19595691/92522633-0ca67480-f1ed-11ea-93bf-b6a4762b99e8.JPG)

**Comment by Rojoyinc** [comment]
opened
![slacv2](https://user-images.githubusercontent.com/19595691/92523315-23999680-f1ee-11ea-932d-2dc9c2b5a6e2.JPG)

It's also not stable. Seems to be crashing a lot and often is running in the background when windows doesn't know it.  SHIFT-TAB sometimes shows it hiding in the background... but a mouse over the tool bar icon does not reveal that it's running. 

example - It would not disconnect or the window would not move (seemed crashed). So I right clicked on the tool bar icon and selected CLOSE DH.    It closed.  I went to run it again fresh and it says it's running already. Though I closed it.  device manager shows it running. I can killed it and re-start but this seems abnormal. 
![slave3](https://user-images.githubusercontent.com/19595691/92523673-c3572480-f1ee-11ea-9f18-8579aa0cb655.JPG)

**Comment by Rojoyinc** [comment]
I have a 64bit machine and OS and just noticed in dev man it says 32?

**Comment by Rojoyinc** [comment]
I'm going to have to wait until I hear from you.  Or I may try the old poth again.  Just tried it again and SLAVE would not slave at all.  I clicked  DISCONNECT dome and it crashed with this. 

![slave4](https://user-images.githubusercontent.com/19595691/92524640-707e6c80-f1f0-11ea-8452-601f4089a37d.JPG)

**Comment by Rojoyinc** [comment]
Sorry for the flooding.  So after hours of tweaking slaving settings...   I did a goto 0  and noticed that the dome wasn't at 0.  It was around 20 degree's off.   AH HA...    But now why?  There does not appear to be any slippage in my drive gear?  (I will go our and heck the hex nut that connects the gear to the rotation motor shaft.   

Is there anything in DH that would misalign the AZ?   I start at home.  (this zero's out at the sensor magnet at home =  0  ). 
so other than gear slippage I can't see any reason why it would be off.   HOWEVER  - Often when I start to slew to a target I find that I have not toggled "SLAVE" dome yet.  The mounts AZ changes toward the target and I then remember to click SLAVE.  (this shouldn't and doesn't mean that they are now off does it?  

Is there any way they would lose sync?    I use to be able to tell the dome to "GOTO" and I could nudge it over to center the shutter and then I could sync.  But the sync button is no longer available to me like was a while back.

**Comment by astroman133** [comment]
While the length of this issue is daunting, at this point virtually all of the problems appear to be either transient issues, configuration issues or pilot error. I am closing this issue. If a demonstrable issue with Device Hub is discovered, a new issue will be created.

**Comment by Rojoyinc** [comment]
It would be shorter if I could have gotten responses to my questions. = (
